name: Sync Repositories

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config --global user.name "Stark"
          git config --global user.email "stark@rwa-wallet.com"

      - name: Push to second repository
        env:
          SECOND_REPO_TOKEN: ${{ secrets.SECOND_REPO_TOKEN }}
        run: |
          echo "Testing repository access..."
          curl -H "Authorization: token ${SECOND_REPO_TOKEN}" https://api.github.com/repos/HelloRWA/bnb3-docs
          
          echo "Adding remote repository..."
          git remote add second-repo https://oauth2:${SECOND_REPO_TOKEN}@github.com/HelloRWA/bnb3-docs.git
          
          echo "Pushing to remote repository..."
          git push second-repo main