name: Sync Repositories

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.SECOND_REPO_TOKEN }}

      - name: Configure Git
        run: |
          git config --global user.name "Stark"
          git config --global user.email "stark@rwa-wallet.com"

      - name: Push to second repository
        env:
          GITHUB_TOKEN: ${{ secrets.SECOND_REPO_TOKEN }}
        run: |
          echo "Adding remote repository..."
          git remote add second-repo https://Stark:${GITHUB_TOKEN}@github.com/HelloRWA/bnb3-docs.git
          
          echo "Rewriting commit author..."
          git filter-branch --env-filter '
            export GIT_AUTHOR_NAME="Stark"
            export GIT_AUTHOR_EMAIL="stark@rwa-wallet.com"
            export GIT_COMMITTER_NAME="Stark"
            export GIT_COMMITTER_EMAIL="stark@rwa-wallet.com"
          ' HEAD
          
          echo "Pushing to remote repository..."
          git push -f second-repo main